apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
  namespace: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://api.back.svc.cluster.local
        image: ghcr.io/do3-2023/sylvain-kube/webapp:latest
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        name: webapp
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        resources:
          limits: {}
          requests:
            memory: 256Mi
            cpu: 250m
      initContainers:
      - command:
        - sh
        - -c
        - 'until nc -zv api.back.svc.cluster.local 80; do echo waiting for API; sleep 2; done;'
        image: busybox
        name: check-api
status: {}
