services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userdemo
      POSTGRES_DB: alcohols
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  api:
    build:
      context: api
      target: prod
    restart: always
    environment:
      PORT: 5000
      DATABASE_URL: postgres://userdemo:password@db:5432/alcohols?sslmode=disable
    volumes:
      - ./api/src:/app/src:ro
    depends_on:
      - db

  webapp:
    build:
      context: webapp
      target: runner
    restart: always
    environment:
      API_URL: "http://api:5000"
    ports:
      - "3000:3000"
    depends_on:
      - api
