services:
  db:
    restart: always
    build:
      context: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userdemo
      POSTGRES_DB: alcohols
    volumes:
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /var/lib/postgresql

  api:
    build:
      context: api
      target: prod
    restart: always
    environment:
      PORT: 5000
      DATABASE_URL: postgres://userdemo:password@db:5432/alcohols?sslmode=disable
    volumes:
      - ./api/src:/app/src:ro
    depends_on:
      - db

  webapp:
    build:
      context: webapp
      target: runner
    restart: always
    environment:
      API_URL: "http://api:5000"
    ports:
      - "3000:3000"
    depends_on:
      - api
