apiVersion: v1
data:
  database_url: cG9zdGdyZXM6Ly91c2VyZGVtbzpwYXNzd29yZEBkYi5kYXRhLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvYWxjb2hvbHM/c3NsbW9kZT1kaXNhYmxlCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: api
  namespace: back
