name: "[CI] API"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "api/**"

jobs:
  build-and-push:
    name: Build and push action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/workflows/build-push-action.yaml
        with:
          registry: ghcr.io
          image-name: api
          context: api
          target: prod
          file: Dockerfile
