name: "[CI] Webapp"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "webapp/**"

jobs:
  build-and-push:
    name: Build and push action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/workflows/build-push-action.yaml
        with:
          registry: ghcr.io
          image-name: webapp
          context: webapp
          target: runner
          file: Dockerfile
